### ISSUE TITLE
Incorrect Display Info

### ISSUE THREAD

**Issue by EN3RGIX** [peterbn/EDx52display#15]
Display doesn't update with system information. Display shows incorrect system information.
Running EDMC and EDDiscovery. Steam key installed in default directories. 

Seems to not be syncing with account profile.

**Comment by peterbn** [comment]
Hi,

If you haven't already, can you please try to install the [latest release](https://github.com/peterbn/EDx52display/releases/tag/v1.5)?

There was an issue recently  (#14) when Odyssey changed the file names of journal files, which could be the cause.

If this doesn't solve the problem, then please let me know exactly how the system information is incorrect. Does it show the right system but wrong info (i.e. wrong planets, etc.), or does it simply show the wrong system when you jump?

**Comment by EN3RGIX** [comment]
This worked. Everything is working normally now.
Thanks!
