### ISSUE TITLE
Stuck at "Initializing device driver..."

### ISSUE THREAD

**Issue by RealDonPhil** [peterbn/EDx52display#18]
Hello, I just don't know what I'm doing wrong at this point and need help. Tried everything I could think of but I can't make it work.
It just gets stuck at "`INFO: Initializing device driver...`" and won't go further. 

I'm on latest release, path to journal files is correct, X52 Pro driver is up to date (as I installed the device on this PC for the first time two weeks ago), running the program as administrator didn't work, tried to run with log parameters and that didn't tell me anything useful...

What am I doing wrong?

**Comment by peterbn** [comment]
Hi - I'm very sorry to hear that it's not working.

Would you mind running it once more with `--log=trace` and posting the full output here (feel free to edit any sensitive path names).

There should be more debug output after the `Initializing device driver...` line, and I just want to see how far it gets. I'd be surprised if that is indeed the last thing it outputs.

**Comment by RealDonPhil** [comment]
I have absolutely no clue what's going on, because today I tried to start it again and it just works. Ran it again with log parameters just to be sure and works as intended. I haven't changed anything, so no idea what caused it to not work initially.

Thanks for the help anyway :)

Closing the thread.

**Comment by peterbn** [comment]
Happy you got it working, even if nobody knows how.

Obligatory: 
<img src="https://www.cipher-it.co.uk/wp-content/uploads/2017/11/ITCrow.jpg">
