### ISSUE TITLE
exe doesn't run

### ISSUE THREAD

**Issue by JVMMs** [peterbn/EDx52display#2]
Hello

So, I've downloaded and unpacked the ZIP. It doesn't contain an `EDx52display.exe` file but contains an `X52MFDDriver.exe`. But when I try to run it, nothing happens.

Does the zip need to be unpacked to a specific folder? Is there something I'm missing? I've redownloaded the file a couple of times, disabled firewall and antivirus checks to make sure they weren't interrupting...

My Elite folders are the default for Steam.

Is there anything I'm missing?

**Comment by peterbn** [comment]
Super strange, I just tried downloading the release from here: https://github.com/peterbn/EDx52display/releases/download/v1.1/EDx52Display.zip and it had all the expected files in it.

Could it be that your antivirus is somehow deleting the exe file? Not that there should be any reason, but they can sometimes be a bit over-zealous.

It shouldn't need any special folders or anything like that, it should just run from the folder it gets unzipped to.

**Comment by JVMMs** [comment]
Oh, that link worked and had the requierd exe. Thanks!

**Comment by peterbn** [comment]
Phew, good to hear.

Enjoy.
