### ISSUE TITLE
Panic Error on Windows 10

### ISSUE THREAD

**Issue by jacobjlandry** [peterbn/EDx52display#4]
When running the app the MFD never updates and I get an error in the console (if I leave it open).

panic: runtime error: slice bounds out of range (screenshot with full error uploaded)

This is the MFD.json file generated:
{"pages":[{"lines":["#  Cargo:   2  #","Consumer Items: 1","Legal Drugs: 1"]},{"lines":["#    System    #","","No EDSM data"]},{"lines":["No FSD Target"]}]}

Also to note: the program won't run for me unless I have Elite Dangerous running, then press windows to minimize and run it

![Screenshot (1)](https://user-images.githubusercontent.com/13259976/87728608-4e301b80-c778-11ea-880c-35aa06bc4338.png)

**Comment by jacobjlandry** [comment]
I'm still seeing this error, but after installing the Logitech X52 Pro Programming tools the display started working. There must have been something in that package that was required.
The system data isn't updating but I just loaded the game as a test, haven't flown around yet so that will probably start working once I change systems and start scanning.

**Comment by peterbn** [comment]
Hi Jacob. You may have been hit by a bug I recently discovered in Shinrarta Dezra, where the current version will just crash.

I recommend that you download the update from here: https://github.com/peterbn/EDx52display/releases/tag/v1.1.1
