### ISSUE TITLE
Initializing device driver

### ISSUE THREAD

**Issue by Carbolemons** [peterbn/EDx52display#9]
![Example](https://user-images.githubusercontent.com/34587311/121401343-3b897c80-c91e-11eb-82bb-57a10800085b.PNG)

Hello there! This tool seems promising, however I seem to be stuck at 
`INFO: Initializing device driver...`

There doesnt seem to be an active report of this happening to some other users in the forum, and this repo seems to have been updated recently. May have to do with my HOTAS or Odyssey, however any advice and steps needed will help!

**Comment by peterbn** [comment]
Hi Carbolemons,

First of all, thank you for the log output.

Could you try to reinstall the Logitech drivers for the HOTAS (https://download01.logi.com/web/ftp/pub/techsupport/simulation/X52_Professional_HOTAS_x64_8_0_213_0.exe) ?

My best guess is that the driver is not currently running on your system, which is a requirement for my software to work.

Regards.

**Comment by Carbolemons** [comment]
Hello there! Thank you for the quick reply! 

I did a _lot_ of further research, apparently the x52 and the x52 Pro -- Despite having the same MFD, the drivers are different for it :(

The standard x52 does not work with this program currently as it appears. No problem! If you don't have the standard x52 then I don't see why ya would write drivers for it. If it is in your interest to extend this to the standard x52 that is on you. 

If i'm not lazy enough, I might just pick up Go and fork this repo and try and adapt it. but otherwise, this looks like solid promising work! 

Fly high commander o7

**Comment by peterbn** [comment]
Hi Carbolemons,

You are correct, this does not work with the standard X52. If that is the HOTAS you have, I'm afraid you are out of luck. One of the big differences between the X52 and the pro is that the X52 (non-pro) simply doesn't support third-party software using the MFD. 

I realise that the project name might be misleading, and will be adding a warning to the README.

Fly safe, commander o7
